### ISSUE TITLE
dyld: Symbol not found: _kABPersonAddressCityKey

### ISSUE THREAD

**Issue by keshavakarthik** [Shopify/mobile-buy-sdk-ios#365]
dyld: Symbol not found: _kABPersonAddressCityKey
  Referenced from: /Users/keshavakarthik/Library/Developer/Xcode/DerivedData/Jumkey_New-cdxmzjlfrhpjqieyfqmuxlbygtlo/Build/Products/Debug-iphonesimulator/Buy.framework/Buy
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/PassKit.framework/PassKit
 in /Users/keshavakarthik/Library/Developer/Xcode/DerivedData/Jumkey_New-cdxmzjlfrhpjqieyfqmuxlbygtlo/Build/Products/Debug-iphonesimulator/Buy.framework/Buy

After updating my Xcode to 8.0 I am getting this issue (for iOS 9). On iOS10 everything is fine.
Please guide me how to fix this

**Comment by bgulanowski** [comment]
This has already been addressed. Please set your CocoaPods version to 2.0.1.
